# Write reference.py in chunks to avoid command length limits
chunks = []
chunks.append("""\"\"\"Curated healthcare reference data.\"\"\"

from __future__ import annotations

__all__ = [
    "DEPARTMENTS",
    "SPECIALTIES",
    "INSURANCE_PLANS",
    "ROOM_TYPES",
    "MEDICATION_FORMS",
    "MEDICATIONS",
    "DIAGNOSIS_CODES",
    "PROCEDURE_CODES",
    "COUNTRIES",
    "STATES",
    "CITIES",
]

DEPARTMENTS = (
    "CARDIOLOGY",
    "ONCOLOGY",
    "NEUROLOGY",
    "ORTHOPEDICS",
    "PEDIATRICS",
    "DERMATOLOGY",
    "PSYCHIATRY",
    "RADIOLOGY",
    "EMERGENCY",
    "SURGERY",
    "INTERNAL_MEDICINE",
    "OBSTETRICS",
    "GYNECOLOGY",
    "UROLOGY",
    "ENT",
    "OPHTHALMOLOGY",
    "ANESTHESIOLOGY",
    "PATHOLOGY",
    "LABORATORY",
    "PHARMACY",
    "NEPHROLOGY",
    "GASTROENTEROLOGY",
    "ENDOCRINOLOGY",
    "PULMONOLOGY",
    "RHEUMATOLOGY",
)

SPECIALTIES = (
    "CARDIOLOGY",
    "ONCOLOGY",
    "NEUROLOGY",
    "ORTHOPEDICS",
    "PEDIATRICS",
    "DERMATOLOGY",
    "PSYCHIATRY",
    "RADIOLOGY",
    "EMERGENCY",
    "SURGERY",
    "INTERNAL_MEDICINE",
    "OBSTETRICS",
    "GYNECOLOGY",
    "UROLOGY",
    "ENT",
    "OPHTHALMOLOGY",
    "ANESTHESIOLOGY",
    "PATHOLOGY",
    "LABORATORY",
    "PHARMACY",
    "NEPHROLOGY",
    "GASTROENTEROLOGY",
    "ENDOCRINOLOGY",
    "PULMONOLOGY",
    "RHEUMATOLOGY",
    "ALLERGY_IMMUNOLOGY",
    "GERIATRICS",
    "INFECTIOUS_DISEASE",
    "HEMATOLOGY",
    "REHABILITATION",
)

INSURANCE_PLANS = (
    "STAR_HEALTH",
    "HDFC_ERGO",
    "ICICI_PRUDENTIAL",
    "BAJAJ_ALLIANZ",
    "NEW_INDIA_ASSURANCE",
    "UNITED_INDIA",
    "SELF_PAY",
    "FAMILY_HEALTH",
    "CRITICAL_ILLNESS",
    "SENIOR_CITIZEN",
    "MATERNITY",
    "INDIVIDUAL",
    "GROUP",
    "TOP_UP",
)

ROOM_TYPES = (
    "ICU",
    "GENERAL",
    "PRIVATE",
    "SEMI_PRIVATE",
    "EMERGENCY",
    "DELUXE",
    "SUITE",
)

MEDICATION_FORMS = (
    "TABLET",
    "CAPSULE",
    "INJECTION",
    "TOPICAL",
    "INHALER",
    "LIQUID",
    "PATCH",
    "DROPS",
    "SUPPOSITORY",
    "INTRAVENOUS",
)

MEDICATIONS = (
    "Paracetamol",
    "Ibuprofen",
    "Amoxicillin",
    "Azithromycin",
    "Omeprazole",
    "Pantoprazole",
    "Metformin",
    "Amlodipine",
    "Atorvastatin",
    "Losartan",
    "Cetirizine",
    "Montelukast",
    "Ranitidine",
    "Diclofenac",
    "Mefenamic Acid",
    "Ciprofloxacin",
    "Levofloxacin",
    "Doxycycline",
    "Clopidogrel",
    "Aspirin",
    "Insulin Glargine",
    "Glibenclamide",
    "Pioglitazone",
    "Sitagliptin",
    "Levothyroxine",
    "Prednisolone",
    "Hydrocortisone",
    "Diazepam",
    "Alprazolam",
    "Sertraline",
    "Escitalopram",
    "Fluoxetine",
    "Amitriptyline",
    "Nortriptyline",
    "Duloxetine",
    "Gabapentin",
    "Pregabalin",
    "Tramadol",
    "Morphine",
    "Fentanyl",
    "Lorazepam",
    "Midazolam",
    "Vecuronium",
    "Rocuronium",
    "Propofol",
    "Sevoflurane",
    "Isoflurane",
    "Ondansetron",
    "Granisetron",
    "Metoclopramide",
    "Domperidone",
    "Loperamide",
    "Oral Rehydration Salts",
    "ORS",
    "Calcium",
    "Vitamin D3",
    "Iron Supplement",
    "Folic Acid",
    "Vitamin B12",
    "Multivitamin",
    "Heparin",
    "Warfarin",
    "Fondaparinux",
    "Rivaroxaban",
    "Apixaban",
    "Dabigatran",
    "Metoprolol",
    "Bisoprolol",
    "Carvedilol",
    "Verapamil",
    "Diltiazem",
    "Digoxin",
    "Furosemide",
    "Spironolactone",
    "Torsemide",
    "Hydrochlorothiazide",
    "Acebutolol",
    "Nebivolol",
    "Clonidine",
    "Methyldopa",
    "Enalapril",
    "Ramipril",
    "Perindopril",
    "Telmisartan",
    "Olmesartan",
    "Valsartan",
    "Irbesartan",
    "Nitroglycerin",
    "Isosorbide Dinitrate",
    "Isosorbide Mononitrate",
    "Ranolazine",
    "Ivabradine",
)
""")

with open('D:/EDS/EDS/eds/domains/healthcare/generators/reference.py', 'w', encoding='utf-8') as f:
    f.write(chunks[0])
    print('Wrote first chunk')
