# Auto-generated by eds-loader schedule — do not edit manually.
# Re-apply user-level environment variables so passwords are available.
$userEnv = [System.Environment]::GetEnvironmentVariables('User')
foreach ($key in $userEnv.Keys) {
    if (-not [System.Environment]::GetEnvironmentVariable($key, 'Process')) {
        [System.Environment]::SetEnvironmentVariable($key, $userEnv[$key], 'Process')
    }
}

$logsDir = 'C:\Users\Mohit Patel\Downloads\EDS\logs'
if (-not (Test-Path $logsDir)) { New-Item -ItemType Directory -Path $logsDir | Out-Null }
$datePart = (Get-Date).ToString('yyyy-MM-dd')
$logFile = "$logsDir\$datePart.task.log"

$timestamp = Get-Date -Format 'yyyy-MM-dd HH:mm:ss'
Add-Content -Path $logFile -Value "[$timestamp] eds-loader scheduled run starting..." -Encoding UTF8

& 'C:\Users\Mohit Patel\AppData\Local\Programs\Python\Python313\Scripts\eds-loader.EXE' run -c 'C:\Users\Mohit Patel\Downloads\EDS\loader.yaml' 2>&1 | ForEach-Object {
    $line = $_ | Out-String
    Add-Content -Path $logFile -Value $line.TrimEnd() -Encoding UTF8
    Write-Host $line.TrimEnd()
}

$exitCode = $LASTEXITCODE
$timestamp = Get-Date -Format 'yyyy-MM-dd HH:mm:ss'
Add-Content -Path $logFile -Value "[$timestamp] eds-loader exited with code: $exitCode" -Encoding UTF8
exit $exitCode
