"""What one simulated day does to the business.

The founding day builds an enterprise that already has years behind it. Every
day after that is this module: a handful of people register, a slice of the
existing base comes back, some of them buy something, stock moves, and points
accrue. Nothing that already happened is touched.

**The day's work is generated by the founding generators.** That is the whole
trick and it is worth being explicit about, because the obvious alternative -
a second implementation of "how a retail business behaves", one for founding
and one for growth - would have to be kept in step with the first for ever and
would drift the week nobody was looking. Instead each generator is handed a
*day-shaped* input: the customer configuration says today is the reference
date, the personas say how many sessions fit in a day, the commerce chain is
shown only the sessions that happened today. What comes back is a day of
business, produced by the same rules as the founding five years.

Four things then have to be true before it can join history, and
:mod:`~eds.domains.retail.temporal.identity` does all four: identifiers
continue rather than restart, codes that render an identifier are rebuilt,
codes that count within a day continue that day's count, and values that must
be unique across the enterprise are checked against everything ever issued.

**Seeded by date, not by position.** Every generator called here is seeded from
:meth:`~eds.domains.retail.temporal.context.BusinessContext.stream`, which
derives from the enterprise seed and the business date. A run that reaches the
fourth of March produces the fourth of March's business, whether it got there
in one run of thirty days, three runs of ten, or a run that failed on the
second and was continued.
"""

from __future__ import annotations

from collections.abc import Mapping
from datetime import date, timedelta

import polars as pl

from eds.core.frames import empty_frame
from eds.core.random_streams import make_rng, resolve_seed
from eds.domains.retail.config import SimulationConfig
from eds.domains.retail.domain.customer.enums import CustomerStatus
from eds.domains.retail.domain.customer.schema import CUSTOMER_LOYALTY
from eds.domains.retail.domain.inventory.schema import INVENTORY
from eds.domains.retail.domain.journey.schema import CUSTOMER_PERSONAS, SESSIONS
from eds.domains.retail.generators.commerce.checkout_generator import generate_checkout_data
from eds.domains.retail.generators.commerce.commerce import generate_commerce_data
from eds.domains.retail.generators.commerce.orders import generate_order_data
from eds.domains.retail.generators.commerce.payments import generate_payment_data
from eds.domains.retail.generators.commerce.returns import generate_return_data
from eds.domains.retail.generators.commerce.reviews import generate_review_data
from eds.domains.retail.generators.commerce.shipment_generator import tracking_number_expression
from eds.domains.retail.generators.commerce.shipments import generate_shipment_data
from eds.domains.retail.generators.customer_data import generate_customer_data
from eds.domains.retail.generators.customers.customer_generator import lifecycle_stage
from eds.domains.retail.generators.inventory.generator import generate_inventory
from eds.domains.retail.generators.journey.browsing import generate_browsing_data
from eds.domains.retail.generators.journey.engagement import generate_engagement_data
from eds.domains.retail.generators.journey.persona_generator import generate_personas
from eds.domains.retail.generators.journey.session_generator import (
    SessionLocations,
    generate_sessions,
)
from eds.domains.retail.temporal.context import BusinessContext
from eds.domains.retail.temporal.identity import (
    continue_daily_sequences,
    disambiguate,
    identity_offsets,
    renumber,
    restate_key_codes,
)

__all__ = [
    "evolve_commerce",
    "evolve_customers",
    "evolve_journey",
    "evolve_master_data",
]

Frames = dict[str, pl.DataFrame]


# --------------------------------------------------------------------------
# Master data: stock moves, everything else is a fixture
# --------------------------------------------------------------------------


def evolve_master_data(
    config: SimulationConfig, context: BusinessContext, history: Mapping[str, pl.DataFrame]
) -> Frames:
    """Move stock to reflect what has been sold, and reorder what ran low.

    Thirteen of the fourteen master datasets are fixtures: a day of trading
    does not open a country, invent a category or take on a supplier. Only
    stock moves, and it moves for a reason that is recorded elsewhere - the
    order lines.

    **Stock is recomputed, not decremented.** Opening stock is a pure function
    of the catalogue and the seed, so it can be rebuilt exactly; cumulative
    demand is a sum over the order history; and the reorder policy is a
    function of both. That makes today's stock a function of history alone,
    which is what lets a run be stopped on any day and picked up on any later
    one without the two disagreeing.

    Args:
        config: Retail settings.
        context: The business date and the enterprise seed.
        history: What already exists. Needs ``products`` and ``warehouses`` to
            rebuild opening stock, and ``orders`` and ``order_lines`` to know
            what has been sold.

    Returns:
        The inventory snapshot as it now stands, or nothing if the catalogue
        is not there to rebuild it from.
    """
    products = history.get("products")
    warehouses = history.get("warehouses")
    if products is None or warehouses is None or products.is_empty() or warehouses.is_empty():
        return {}

    opening = generate_inventory(
        config.master_data, products, warehouses, resolve_seed(config.platform.seed)
    )
    sold = _units_sold(history, context.business_date)
    return {"inventory": _restocked(opening, sold)}


def _units_sold(history: Mapping[str, pl.DataFrame], upto: date) -> pl.DataFrame:
    """Return how many units of each product have been ordered so far.

    Args:
        history: What already exists.
        upto: Orders placed after this date are not counted - they have not
            happened yet from the point of view of this business day.

    Returns:
        One row per product that has sold anything, with a ``_sold`` column.
    """
    orders = history.get("orders")
    lines = history.get("order_lines")
    if orders is None or lines is None or orders.is_empty() or lines.is_empty():
        return pl.DataFrame(
            {"product_id": [], "_sold": []},
            schema={"product_id": pl.Int64, "_sold": pl.Int64},
        )
    placed = orders.filter(pl.col("order_date") <= upto).select("order_id")
    return (
        lines.join(placed, on="order_id", how="inner")
        .group_by("product_id")
        .agg(pl.col("quantity").sum().cast(pl.Int64).alias("_sold"))
    )


def _restocked(opening: pl.DataFrame, sold: pl.DataFrame) -> pl.DataFrame:
    """Apply cumulative demand and the reorder policy to opening stock.

    Demand for a product is shared across the warehouses that stock it, the
    remainder going to the lowest-numbered rows so the split is reproducible.
    A line that would fall to or below its reorder point is replenished in
    whole reorder lots - the fixed-lot policy the reorder columns describe.

    Args:
        opening: Stock as the founding day created it.
        sold: Units ordered per product.

    Returns:
        The inventory dataset, in schema order.
    """
    positions = pl.int_range(pl.len(), dtype=pl.Int64).over("product_id")
    lines_per_product = pl.len().over("product_id")
    demand = pl.col("_sold").fill_null(0)
    share = demand // lines_per_product + (positions < demand % lines_per_product).cast(pl.Int64)

    remaining = pl.col("quantity_on_hand") - pl.col("_share")
    lot = pl.max_horizontal(pl.col("reorder_quantity"), pl.lit(1, dtype=pl.Int64))
    shortfall = pl.col("reorder_point") + lot - remaining
    lots = (shortfall.cast(pl.Float64) / lot.cast(pl.Float64)).ceil().cast(pl.Int64)

    return (
        opening.join(sold, on="product_id", how="left")
        .with_columns(share.alias("_share"))
        .with_columns(
            pl.when(remaining > pl.col("reorder_point"))
            .then(remaining)
            .otherwise(remaining + lots * lot)
            .alias("quantity_on_hand")
        )
        .select(*INVENTORY.columns)
    )


# --------------------------------------------------------------------------
# Customers: a few people join, and everybody's points catch up
# --------------------------------------------------------------------------


def evolve_customers(
    config: SimulationConfig,
    context: BusinessContext,
    upstream: Mapping[str, pl.DataFrame],
    history: Mapping[str, pl.DataFrame],
) -> Frames:
    """Register today's new customers and bring loyalty balances up to date.

    Args:
        config: Retail settings.
        context: The business date and the enterprise seed.
        upstream: The geography datasets the plan says this stage requires.
        history: What already exists, including the ``orders`` that loyalty
            balances are earned on.

    Returns:
        The datasets this day changed. An enterprise that acquires nobody and
        sells nothing changes none of them.

    Raises:
        KeyError: If a geography dataset is missing.
        ValueError: If a geography dataset is empty.
    """
    produced: Frames = {}
    if config.evolution.new_customers_per_day:
        produced.update(_registered_today(config, context, upstream, history))

    accrued = _accrued_loyalty(config, context, history, produced.get("customer_loyalty"))
    if accrued is not None:
        produced["customer_loyalty"] = accrued
    return produced


def _registered_today(
    config: SimulationConfig,
    context: BusinessContext,
    upstream: Mapping[str, pl.DataFrame],
    history: Mapping[str, pl.DataFrame],
) -> Frames:
    """Generate the customers who register on this business date.

    The generator is asked for a cohort as of today, and the cohort is then
    settled *on* today: the founding generator spreads registration across
    five years because that is what a founding snapshot means, and a day's
    intake all joined on the day.

    Args:
        config: Retail settings.
        context: The business date and the enterprise seed.
        upstream: The geography datasets.
        history: What already exists.

    Returns:
        The four customer datasets for the new cohort.

    Raises:
        KeyError: If a geography dataset is missing.
        ValueError: If a geography dataset is empty.
    """
    today = context.business_date
    settings = config.customers.model_copy(
        update={
            "customer_count": config.evolution.new_customers_per_day,
            "reference_date": today,
        }
    )
    cohort = generate_customer_data(
        _seeded(config, context.stream("customers")).model_copy(update={"customers": settings}),
        upstream,
    )

    frames = dict(cohort.datasets)
    frames = renumber(frames, identity_offsets(history, frames))
    frames = restate_key_codes(frames)
    frames["customers"] = _joined_today(frames["customers"], today)
    frames["customers"] = _globally_unique(frames["customers"], history.get("customers"))
    frames["customer_loyalty"] = _enrolled_today(frames["customer_loyalty"], today)
    return frames


def _joined_today(customers: pl.DataFrame, today: date) -> pl.DataFrame:
    """Settle a cohort's registration on one business date.

    Args:
        customers: The generated cohort.
        today: The business date.

    Returns:
        The cohort, registered today, with the lifecycle stage re-derived from
        the tenure that gives them - the same rule the generator applies.
    """
    time_of_day = pl.col("created_at") - pl.col("created_at").dt.truncate("1d")
    registered_at = pl.lit(today).cast(pl.Datetime("us")) + time_of_day
    stages = [
        str(lifecycle_stage(CustomerStatus(status), today, today))
        for status in customers["status"].to_list()
    ]
    return customers.with_columns(
        pl.lit(today).cast(pl.Date).alias("registration_date"),
        registered_at.alias("created_at"),
        registered_at.alias("updated_at"),
        pl.Series("lifecycle_stage", stages, dtype=pl.String),
    )


def _enrolled_today(loyalty: pl.DataFrame, today: date) -> pl.DataFrame:
    """Enrol a cohort's loyalty accounts on the day they registered.

    Args:
        loyalty: The generated loyalty rows.
        today: The business date.

    Returns:
        The rows, enrolled today with nothing yet earned. A balance carried in
        on the first day would be points nobody had spent anything for.
    """
    return loyalty.with_columns(
        pl.lit(today).cast(pl.Date).alias("enrollment_date"),
        pl.lit(0, dtype=pl.Int64).alias("points_balance"),
    )


def _globally_unique(cohort: pl.DataFrame, history: pl.DataFrame | None) -> pl.DataFrame:
    """Rewrite contact details that collide with ones already issued.

    Args:
        cohort: Today's customers.
        history: Every customer registered before today, or ``None``.

    Returns:
        The cohort, with unique email addresses and phone numbers across the
        whole enterprise. Both fallbacks are the generator's own.
    """
    if history is None or history.is_empty():
        return cohort
    with_email = disambiguate(
        cohort,
        "email",
        history["email"].to_list(),
        lambda value, key: f"{value.split('@')[0]}.{key}@{value.split('@')[-1]}",
        "customer_id",
    )
    return disambiguate(
        with_email,
        "phone",
        history["phone"].to_list(),
        lambda _, key: f"+1-999-{key // 10_000:03d}-{key % 10_000:04d}",
        "customer_id",
    )


def _accrued_loyalty(
    config: SimulationConfig,
    context: BusinessContext,
    history: Mapping[str, pl.DataFrame],
    joining: pl.DataFrame | None,
) -> pl.DataFrame | None:
    """Bring every loyalty balance up to what lifetime spending has earned.

    The balance is the greater of what was recorded and what spending entitles
    the customer to, which is the one formula that makes accumulation both
    monotonic and independent of how a run was divided into days. A balance
    can never fall, and recomputing it twice cannot double it.

    Args:
        config: Retail settings.
        context: The business date and the enterprise seed.
        history: What already exists.
        joining: Today's new loyalty rows, if anybody registered.

    Returns:
        Every loyalty row that now exists, or ``None`` if there is nothing to
        bring up to date.
    """
    existing = history.get("customer_loyalty")
    if existing is None or existing.is_empty():
        return joining

    orders = history.get("orders")
    if orders is None or orders.is_empty():
        updated = existing
    else:
        spend = (
            orders.filter(pl.col("order_date") <= context.business_date)
            .group_by("customer_id")
            .agg(pl.col("total_amount").sum().alias("_spend"))
        )
        rate = config.evolution.loyalty_points_per_unit
        earned = (pl.col("_spend").fill_null(0.0) * rate).floor()
        updated = (
            existing.join(spend, on="customer_id", how="left")
            .with_columns(
                pl.max_horizontal(pl.col("points_balance"), earned.cast(pl.Int64)).alias(
                    "points_balance"
                )
            )
            .select(*CUSTOMER_LOYALTY.columns)
        )

    if joining is None or joining.is_empty():
        return updated
    return pl.concat([updated, joining.select(*CUSTOMER_LOYALTY.columns)], how="vertical")


# --------------------------------------------------------------------------
# Journey: who came back today, and what they looked at
# --------------------------------------------------------------------------


def evolve_journey(
    config: SimulationConfig,
    context: BusinessContext,
    upstream: Mapping[str, pl.DataFrame],
    history: Mapping[str, pl.DataFrame],
) -> Frames:
    """Give personas to new customers and a day of browsing to active ones.

    Args:
        config: Retail settings.
        context: The business date and the enterprise seed.
        upstream: The datasets the plan says this stage requires.
        history: What already exists.

    Returns:
        The datasets this day changed.

    Raises:
        KeyError: If a required upstream dataset is missing.
        ValueError: If a customer selected for a session has no address.
    """
    today = context.business_date
    customers = upstream["customers"]
    # Strictly before today: the founding generator will not open a session on
    # the day somebody registered, and neither does a day of trading.
    resident = customers.filter(pl.col("registration_date") < today)
    if resident.is_empty():
        return {}

    produced: Frames = {}
    # Everybody gets a persona the day they register; only those who
    # registered before today can open a session on it.
    personas = _personas_for(config, context, customers, history, produced)
    eligible = personas.join(resident.select("customer_id"), on="customer_id", how="semi")
    if eligible.is_empty():
        return produced

    active = _active_today(config, context, eligible)
    if active.is_empty():
        return produced

    sessions = _sessions_today(config, context, active, resident, upstream)
    if sessions.is_empty():
        return produced
    produced["sessions"] = renumber(
        {"sessions": sessions}, identity_offsets(history, ["sessions"])
    )["sessions"]

    everything = {**upstream, "customer_personas": personas, "sessions": produced["sessions"]}
    browsing = generate_browsing_data(_seeded(config, context.stream("browsing")), everything)
    produced.update(renumber(dict(browsing.datasets), identity_offsets(history, browsing.datasets)))

    seen = {**everything, **browsing.datasets, **produced}
    engagement = generate_engagement_data(_seeded(config, context.stream("engagement")), seen)
    produced.update(
        renumber(dict(engagement.datasets), identity_offsets(history, engagement.datasets))
    )
    return produced


def _personas_for(
    config: SimulationConfig,
    context: BusinessContext,
    customers: pl.DataFrame,
    history: Mapping[str, pl.DataFrame],
    produced: Frames,
) -> pl.DataFrame:
    """Return every persona that exists once every customer has one.

    A persona is assigned when a customer arrives and is not revisited, so
    this only ever generates for customers who have none.

    Args:
        config: Retail settings.
        context: The business date and the enterprise seed.
        customers: Every customer the enterprise has.
        history: What already exists.
        produced: Today's output, added to if personas were generated.

    Returns:
        The complete persona set, historical rows first.
    """
    known = history.get("customer_personas")
    if known is None or known.is_empty():
        assigned = empty_frame(CUSTOMER_PERSONAS)
        waiting = customers
    else:
        assigned = known
        waiting = customers.join(known.select("customer_id"), on="customer_id", how="anti")

    if waiting.is_empty():
        return assigned

    fresh = generate_personas(
        config.customers.model_copy(update={"reference_date": context.business_date}),
        config.journey,
        waiting.sort("customer_id"),
        context.stream("personas"),
    )
    offsets = identity_offsets(history, ["customer_personas"])
    fresh = renumber({"customer_personas": fresh}, offsets)["customer_personas"]
    produced["customer_personas"] = fresh
    return pl.concat([assigned, fresh.select(*CUSTOMER_PERSONAS.columns)], how="vertical")


def _active_today(
    config: SimulationConfig, context: BusinessContext, personas: pl.DataFrame
) -> pl.DataFrame:
    """Choose who comes back today, and how often.

    Selection is weighted by the persona's own session frequency, so a
    customer the founding day decided browses constantly is likelier to appear
    than one who barely visits. The frequency is then rewritten to a day's
    worth: the founding value counts sessions over years.

    Args:
        config: Retail settings.
        context: The business date and the enterprise seed.
        personas: Every persona that exists.

    Returns:
        The personas of the customers active today, with a daily session
        frequency.
    """
    rng = make_rng(context.stream("active"), "active_customers")
    frequencies: list[int] = personas["session_frequency"].to_list()
    if not frequencies:
        return personas.clear()
    busiest = max(max(frequencies), 1)
    rate = config.evolution.active_customer_rate
    ceiling = config.evolution.max_daily_sessions

    chosen: list[bool] = []
    sessions: list[int] = []
    for frequency in frequencies:
        # A customer twice as busy as the average is twice as likely back.
        appetite = min(1.0, rate * (1.0 + frequency / busiest))
        active = rng.random() < appetite
        chosen.append(active)
        sessions.append(rng.randint(1, ceiling) if active else 0)

    return (
        personas.with_columns(
            pl.Series("_active", chosen, dtype=pl.Boolean),
            pl.Series("_today", sessions, dtype=pl.Int64),
        )
        .filter(pl.col("_active"))
        .with_columns(pl.col("_today").alias("session_frequency"))
        .select(*CUSTOMER_PERSONAS.columns)
    )


def _sessions_today(
    config: SimulationConfig,
    context: BusinessContext,
    active: pl.DataFrame,
    resident: pl.DataFrame,
    upstream: Mapping[str, pl.DataFrame],
) -> pl.DataFrame:
    """Generate one day of sessions for the customers who came back.

    The founding generator opens sessions between the day after a customer
    registered and the reference date. Telling it that everybody registered
    yesterday and that today is the reference date leaves it exactly one day
    to work in, which is what a tick is.

    Args:
        config: Retail settings.
        context: The business date and the enterprise seed.
        active: The personas of today's active customers.
        resident: Customers who registered before today.
        upstream: The datasets the plan says this stage requires.

    Returns:
        Today's sessions, numbered from one.

    Raises:
        KeyError: If a required upstream dataset is missing.
        ValueError: If an active customer has no primary address.
    """
    today = context.business_date
    browsing_today = resident.join(active.select("customer_id"), on="customer_id", how="semi")
    if browsing_today.is_empty():
        return empty_frame(SESSIONS)

    locations = SessionLocations.from_frames(upstream["customer_addresses"], upstream["countries"])
    one_day = browsing_today.with_columns(
        pl.lit(today - timedelta(days=1)).cast(pl.Date).alias("registration_date")
    )
    return generate_sessions(
        config.customers.model_copy(update={"reference_date": today}),
        config.journey,
        active,
        one_day,
        locations,
        context.stream("sessions"),
    )


# --------------------------------------------------------------------------
# Commerce: what today's browsing turned into
# --------------------------------------------------------------------------


def evolve_commerce(
    config: SimulationConfig,
    context: BusinessContext,
    upstream: Mapping[str, pl.DataFrame],
    history: Mapping[str, pl.DataFrame],
) -> Frames:
    """Turn today's browsing into carts, orders, money and parcels.

    The chain is the founding one, F004 through F010, shown only what happened
    today: today's sessions, today's product views, today's wishlists. Its
    dimensions - customers, addresses, products, personas - are the whole
    enterprise, because a customer who registered two years ago can still buy
    something this morning.

    Args:
        config: Retail settings.
        context: The business date and the enterprise seed.
        upstream: The datasets the plan says this stage requires.
        history: What already exists.

    Returns:
        The fifteen commerce datasets for today, or nothing if nobody browsed.

    Raises:
        KeyError: If a required upstream dataset is missing.
        ValueError: If a required upstream dataset is unusable.
    """
    sessions = upstream["sessions"].filter(pl.col("start_time").dt.date() == context.business_date)
    if sessions.is_empty():
        return {}

    opened = sessions.select("session_id")
    today = {
        **upstream,
        "sessions": sessions,
        "product_views": upstream["product_views"].join(opened, on="session_id", how="semi"),
        "wishlists": upstream["wishlists"].join(
            upstream["product_views"]
            .join(opened, on="session_id", how="semi")
            .select("product_view_id"),
            on="product_view_id",
            how="semi",
        ),
    }

    settings = _seeded(config, context.stream("commerce"))
    commerce = generate_commerce_data(settings, today)
    checkout = generate_checkout_data(settings, {**today, **commerce.datasets})
    orders = generate_order_data(settings, {**today, **commerce.datasets, **checkout.datasets})
    placed = {**today, **commerce.datasets, **checkout.datasets, **orders.datasets}
    payments = generate_payment_data(settings, placed)
    shipments = generate_shipment_data(settings, {**placed, **payments.datasets})
    fulfilled = {**placed, **payments.datasets, **shipments.datasets}
    returns = generate_return_data(settings, fulfilled)
    reviews = generate_review_data(settings, {**fulfilled, **returns.datasets})

    produced: Frames = {
        **commerce.datasets,
        **checkout.datasets,
        **orders.datasets,
        **payments.datasets,
        **shipments.datasets,
        **returns.datasets,
        **reviews.datasets,
    }
    produced = renumber(produced, identity_offsets(history, produced))
    # The tracking number is a scramble of the shipment identifier, so moving
    # the identifier makes it a lie - and, unlike a rendering, a colliding one.
    produced["shipments"] = produced["shipments"].with_columns(
        tracking_number_expression(config.shipments.tracking_number_prefix)
    )
    return continue_daily_sequences(produced, history, _code_prefixes(config))


def _code_prefixes(config: SimulationConfig) -> dict[str, str]:
    """Return the configured leading token of each daily business code.

    Args:
        config: Retail settings.

    Returns:
        Dataset name to prefix.
    """
    return {
        "orders": config.orders.order_number_prefix,
        "payments": config.payments.payment_reference_prefix,
        "shipments": config.shipments.shipment_number_prefix,
        "returns": config.returns.return_number_prefix,
        "reviews": config.reviews.review_number_prefix,
    }


def _seeded(config: SimulationConfig, seed: int) -> SimulationConfig:
    """Return the settings with one day's seed bound to them.

    Args:
        config: Retail settings.
        seed: The day's seed for one named stream.

    Returns:
        The same settings, generating for this day.
    """
    return config.model_copy(update={"platform": config.platform.model_copy(update={"seed": seed})})
