"""Keeping business identities stable while the business grows.

A day's work is generated by the same generators that built the founding
enterprise, and those generators always number from one. Two customers called
number 1 is not a numbering problem, it is a *business* problem: yesterday's
customer 1 and today's customer 1 are different people, and every order either
of them placed points at the wrong one.

So a day's output is renumbered before it joins history: every primary key is
shifted past the largest one already issued, and every foreign key that points
at something generated *on the same day* is shifted with it. A foreign key
that points at something older - an order's customer, a cart item's product -
is already correct and is left alone.

**The shift is driven by the schema, not by a list.** Which column is the
primary key and which columns are foreign keys is already declared, once, in
:class:`~eds.core.schema.Dataset`. Reading those declarations means a new
dataset is renumbered correctly the day it is declared, with no second list to
keep in step.

Two things do not survive a shift, and both are repaired here:

* **Codes derived from an identifier.** ``CUST-00000042`` is a rendering of
  customer 42. Shift the customer and the rendering is a lie.
* **Codes that count within a day.** ``ORD-20260304-000001`` is the first
  order *on the fourth of March*. A later day can ship or refund against that
  same date, so its sequence must continue from what that date already holds
  rather than restart. History keeps its numbers; the new rows take the next
  ones.

Values that must be unique across the whole enterprise - an email address, a
phone number - are checked against everything already issued and rewritten
with the generator's own fallback rule when they collide. Same rule, wider
memory.
"""

from __future__ import annotations

from collections.abc import Callable, Iterable, Mapping
from dataclasses import dataclass
from typing import Final

import polars as pl

from eds.domains.retail.temporal.datasets import retail_dataset

__all__ = [
    "DAILY_SEQUENCES",
    "KEY_CODES",
    "DailySequence",
    "DerivedCode",
    "continue_daily_sequences",
    "disambiguate",
    "identity_offsets",
    "last_identifier",
    "renumber",
    "restate_key_codes",
]


def last_identifier(frame: pl.DataFrame | None, column: str) -> int:
    """Return the largest identifier already issued in a dataset.

    Args:
        frame: The dataset's history, or ``None`` if it has none.
        column: The identifier column.

    Returns:
        The largest value, or ``0`` for an absent or empty dataset - which
        makes the first identifier issued ``1``, exactly as a founding run
        would.
    """
    if frame is None or frame.is_empty() or column not in frame.columns:
        return 0
    largest = frame[column].max()
    return largest if isinstance(largest, int) else 0


def identity_offsets(history: Mapping[str, pl.DataFrame], names: Iterable[str]) -> dict[str, int]:
    """Return how far past history each dataset's new identifiers must start.

    Args:
        history: What already exists, keyed by dataset name.
        names: The datasets being generated today.

    Returns:
        Dataset name to offset. A dataset with no history offsets by zero.
    """
    return {
        name: last_identifier(history.get(name), retail_dataset(name).primary_key) for name in names
    }


def renumber(
    produced: Mapping[str, pl.DataFrame], offsets: Mapping[str, int]
) -> dict[str, pl.DataFrame]:
    """Shift a day's identifiers past everything already issued.

    Args:
        produced: The day's datasets, numbered from one.
        offsets: How far to shift each dataset, from :func:`identity_offsets`.
            A dataset absent from this mapping is one whose rows were *not*
            generated today, so foreign keys pointing at it are already
            correct and are left untouched.

    Returns:
        The same datasets, renumbered.

    Raises:
        KeyError: If a dataset is not one Retail declares.
    """
    shifted: dict[str, pl.DataFrame] = {}
    for name, frame in produced.items():
        declaration = retail_dataset(name)
        updates = []
        if step := offsets.get(name, 0):
            updates.append(pl.col(declaration.primary_key) + step)
        for key in declaration.foreign_keys:
            if key.column == declaration.primary_key:
                continue
            if step := offsets.get(key.references, 0):
                updates.append(pl.col(key.column) + step)
        shifted[name] = frame.with_columns(updates) if updates else frame
    return shifted


@dataclass(frozen=True, slots=True)
class DerivedCode:
    """A business code that is a rendering of an identifier.

    Attributes:
        dataset: Which dataset carries it.
        column: The code column.
        source: The identifier it renders.
        prefix: The code's leading token.
        width: How many digits the identifier is padded to.
    """

    dataset: str
    column: str
    source: str
    prefix: str
    width: int

    def expression(self) -> pl.Expr:
        """Return the expression that rebuilds this code from its identifier."""
        return pl.concat_str(
            [
                pl.lit(self.prefix),
                pl.col(self.source).cast(pl.String).str.zfill(self.width),
            ],
            separator="-",
        ).alias(self.column)


#: Codes that must be rebuilt after renumbering, because they render an
#: identifier that moved. Both mirror a ``format_code`` call in the generator
#: that issues them, and a test pins them against a founding run's output.
KEY_CODES: Final[tuple[DerivedCode, ...]] = (
    DerivedCode("customers", "customer_number", "customer_id", "CUST", 8),
    DerivedCode("customer_loyalty", "loyalty_number", "customer_id", "LOY", 8),
)


def restate_key_codes(produced: Mapping[str, pl.DataFrame]) -> dict[str, pl.DataFrame]:
    """Rebuild every code that renders an identifier.

    Args:
        produced: The day's datasets, already renumbered.

    Returns:
        The same datasets, with identifier-derived codes rebuilt.
    """
    restated = dict(produced)
    for code in KEY_CODES:
        frame = restated.get(code.dataset)
        if frame is not None and code.column in frame.columns:
            restated[code.dataset] = frame.with_columns(code.expression())
    return restated


@dataclass(frozen=True, slots=True)
class DailySequence:
    """A business code that counts within one calendar day.

    Attributes:
        dataset: Which dataset carries it.
        column: The code column.
        moment_column: The column the day is read from. The generators build
            the day from a timestamp and drop it again, so the persisted
            dataset carries the timestamp rather than the date.
        width: How many digits the sequence is padded to.
    """

    dataset: str
    column: str
    moment_column: str
    width: int

    def day(self, frame: pl.DataFrame) -> pl.Expr:
        """Return the expression giving each row's calendar day.

        Args:
            frame: The frame the expression will be evaluated against, read
                only for the column's type.

        Returns:
            The day, whether the column holds a date or a timestamp.
        """
        moment = pl.col(self.moment_column)
        return moment.dt.date() if frame.schema[self.moment_column] != pl.Date else moment


#: The five ``PREFIX-YYYYMMDD-NNNNNN`` codes. Each restarts daily in the
#: generator that issues it, which is correct within one run and wrong across
#: days: a Tuesday's trading can produce a shipment, refund or review dated on
#: a Friday that a later day will also write to.
DAILY_SEQUENCES: Final[tuple[DailySequence, ...]] = (
    DailySequence("orders", "order_number", "order_date", 6),
    DailySequence("payments", "payment_reference", "created_at", 6),
    DailySequence("shipments", "shipment_number", "created_at", 6),
    DailySequence("returns", "return_number", "requested_at", 6),
    DailySequence("reviews", "review_number", "created_at", 6),
)


def continue_daily_sequences(
    produced: Mapping[str, pl.DataFrame],
    history: Mapping[str, pl.DataFrame],
    prefixes: Mapping[str, str],
) -> dict[str, pl.DataFrame]:
    """Continue each daily sequence from where history left it.

    History is read and never written: a code already issued keeps the number
    it was issued with, whatever a later day adds to the same date.

    Args:
        produced: The day's datasets, already renumbered.
        history: What already exists, keyed by dataset name.
        prefixes: Dataset name to the configured leading token.

    Returns:
        The same datasets, with daily sequences continued.
    """
    continued = dict(produced)
    for sequence in DAILY_SEQUENCES:
        frame = continued.get(sequence.dataset)
        if frame is None or frame.is_empty() or sequence.column not in frame.columns:
            continue
        prefix = prefixes.get(sequence.dataset)
        if prefix is None:
            continue
        # Sorting by the primary key restores the order the generator assigned
        # identifiers in, which is the order the sequence must count in.
        key = retail_dataset(sequence.dataset).primary_key
        frame = frame.sort(key)
        day = sequence.day(frame)
        position = pl.int_range(pl.len(), dtype=pl.UInt32).over(day) + 1
        taken = _issued_per_day(history.get(sequence.dataset), sequence)
        continued[sequence.dataset] = frame.with_columns(
            pl.concat_str(
                [
                    pl.lit(prefix),
                    day.dt.strftime("%Y%m%d"),
                    (position + taken).cast(pl.String).str.zfill(sequence.width),
                ],
                separator="-",
            ).alias(sequence.column)
        )
    return continued


def _issued_per_day(frame: pl.DataFrame | None, sequence: DailySequence) -> pl.Expr:
    """Build an expression giving how many codes a day already holds.

    Args:
        frame: The dataset's history, or ``None``.
        sequence: The sequence being continued.

    Returns:
        An expression yielding the count, which is a constant zero when there
        is no history to continue from.
    """
    if frame is None or frame.is_empty() or sequence.moment_column not in frame.columns:
        return pl.lit(0, dtype=pl.UInt32)
    counts = frame.select(sequence.day(frame).alias("_day")).group_by("_day").len()
    days = counts["_day"].to_list()
    totals = [int(value) for value in counts["len"].to_list()]
    return sequence.day(frame).replace_strict(days, totals, default=0, return_dtype=pl.UInt32)


def disambiguate(
    frame: pl.DataFrame,
    column: str,
    taken: Iterable[str],
    fallback: Callable[[str, int], str],
    key_column: str,
) -> pl.DataFrame:
    """Rewrite values that collide with ones already issued.

    The generators guarantee uniqueness within a run by remembering what they
    have issued and falling back to an identifier-bearing variant on collision.
    That memory ends when the run does, so it is applied again here against
    everything the enterprise has ever issued.

    Args:
        frame: The day's rows.
        column: The column that must be unique across the enterprise.
        taken: Values already issued.
        fallback: How to rewrite a colliding value, given the value and the
            row's identifier. Mirrors the generator's own fallback.
        key_column: The identifier column the fallback uses.

    Returns:
        The rows, with collisions rewritten.
    """
    if frame.is_empty() or column not in frame.columns:
        return frame
    seen = set(taken)
    values: list[str] = frame[column].to_list()
    keys: list[int] = frame[key_column].to_list()
    resolved: list[str] = []
    for value, key in zip(values, keys, strict=True):
        chosen = value if value not in seen else fallback(value, key)
        seen.add(chosen)
        resolved.append(chosen)
    return frame.with_columns(pl.Series(column, resolved, dtype=pl.String))
