"""Curated healthcare reference data."""

from __future__ import annotations

__all__ = [
    "DEPARTMENTS",
    "SPECIALTIES",
    "INSURANCE_PLANS",
    "ROOM_TYPES",
    "MEDICATION_FORMS",
    "MEDICATIONS",
    "DIAGNOSIS_CODES",
    "PROCEDURE_CODES",
    "COUNTRIES",
    "STATES",
    "CITIES",
]

DEPARTMENTS = (
    "CARDIOLOGY",
    "ONCOLOGY",
    "NEUROLOGY",
    "ORTHOPEDICS",
    "PEDIATRICS",
    "DERMATOLOGY",
    "PSYCHIATRY",
    "RADIOLOGY",
    "EMERGENCY",
    "SURGERY",
    "INTERNAL_MEDICINE",
    "OBSTETRICS",
    "GYNECOLOGY",
    "UROLOGY",
    "ENT",
    "OPHTHALMOLOGY",
    "ANESTHESIOLOGY",
    "PATHOLOGY",
    "LABORATORY",
    "PHARMACY",
    "NEPHROLOGY",
    "GASTROENTEROLOGY",
    "ENDOCRINOLOGY",
    "PULMONOLOGY",
    "RHEUMATOLOGY",
)

SPECIALTIES = (
    "CARDIOLOGY",
    "ONCOLOGY",
    "NEUROLOGY",
    "ORTHOPEDICS",
    "PEDIATRICS",
    "DERMATOLOGY",
    "PSYCHIATRY",
    "RADIOLOGY",
    "EMERGENCY",
    "SURGERY",
    "INTERNAL_MEDICINE",
    "OBSTETRICS",
    "GYNECOLOGY",
    "UROLOGY",
    "ENT",
    "OPHTHALMOLOGY",
    "ANESTHESIOLOGY",
    "PATHOLOGY",
    "LABORATORY",
    "PHARMACY",
    "NEPHROLOGY",
    "GASTROENTEROLOGY",
    "ENDOCRINOLOGY",
    "PULMONOLOGY",
    "RHEUMATOLOGY",
    "ALLERGY_IMMUNOLOGY",
    "GERIATRICS",
    "INFECTIOUS_DISEASE",
    "HEMATOLOGY",
    "REHABILITATION",
)

INSURANCE_PLANS = (
    "STAR_HEALTH",
    "HDFC_ERGO",
    "ICICI_PRUDENTIAL",
    "BAJAJ_ALLIANZ",
    "NEW_INDIA_ASSURANCE",
    "UNITED_INDIA",
    "SELF_PAY",
    "FAMILY_HEALTH",
    "CRITICAL_ILLNESS",
    "SENIOR_CITIZEN",
    "MATERNITY",
    "INDIVIDUAL",
    "GROUP",
    "TOP_UP",
)

ROOM_TYPES = (
    "ICU",
    "GENERAL",
    "PRIVATE",
    "semi-private",
    "EMERGENCY",
    "DELUXE",
    "SUITE",
)

MEDICATION_FORMS = (
    "TABLET",
    "CAPSULE",
    "INJECTION",
    "TOPICAL",
    "INHALER",
    "LIQUID",
    "PATCH",
    "DROPS",
    "SUPPOSITORY",
    "INTRAVENOUS",
)

MEDICATIONS = (
    "Paracetamol",
    "Ibuprofen",
    "Amoxicillin",
    "Azithromycin",
    "Omeprazole",
    "Pantoprazole",
    "Metformin",
    "Amlodipine",
    "Atorvastatin",
    "Losartan",
    "Cetirizine",
    "Montelukast",
    "Ranitidine",
    "Diclofenac",
    "Mefenamic Acid",
    "Ciprofloxacin",
    "Levofloxacin",
    "Doxycycline",
    "Clopidogrel",
    "Aspirin",
    "Insulin Glargine",
    "Glibenclamide",
    "Pioglitazone",
    "Sitagliptin",
    "Levothyroxine",
    "Prednisolone",
    "Hydrocortisone",
    "Diazepam",
    "Alprazolam",
    "Sertraline",
    "Escitalopram",
    "Fluoxetine",
    "Amitriptyline",
    "Nortriptyline",
    "Duloxetine",
    "Gabapentin",
    "Pregabalin",
    "Tramadol",
    "Morphine",
    "Fentanyl",
    "Lorazepam",
    "Midazolam",
    "Vecuronium",
    "Rocuronium",
    "Propofol",
    "Sevoflurane",
    "Isoflurane",
    "Ondansetron",
    "Granisetron",
    "Metoclopramide",
    "Domperidone",
    "Loperamide",
    "Oral Rehydration Salts",
    "ORS",
    "Calcium",
    "Vitamin D3",
    "Iron Supplement",
    "Folic Acid",
    "Vitamin B12",
    "Multivitamin",
    "Heparin",
    "Warfarin",
    "Fondaparinux",
    "Rivaroxaban",
    "Apixaban",
    "Dabigatran",
    "Metoprolol",
    "Bisoprolol",
    "Carvedilol",
    "Verapamil",
    "Diltiazem",
    "Digoxin",
    "Furosemide",
    "Spironolactone",
    "Torsemide",
    "Hydrochlorothiazide",
    "Acebutolol",
    "Nebivolol",
    "Clonidine",
    "Methyldopa",
    "Enalapril",
    "Ramipril",
    "Perindopril",
    "Telmisartan",
    "Olmesartan",
    "Valsartan",
    "Irbesartan",
    "Nitroglycerin",
    "Isosorbide Dinitrate",
    "Isosorbide Mononitrate",
    "Ranolazine",
    "Ivabradine",
)


DIAGNOSIS_CODES = (
    {"code": "A00", "description": "Cholera", "category": "INFECTIOUS"},
    {"code": "C00", "description": "Malignant neoplasm of lip", "category": "NEOPLASMS"},
    {"code": "D50", "description": "Iron deficiency anemia", "category": "BLOOD"},
    {"code": "E00", "description": "Congenital iodine-deficiency syndrome", "category": "ENDOCRINE"},
    {"code": "F01", "description": "Vascular dementia", "category": "MENTAL"},
    {"code": "A01", "description": "Typhoid and paratyphoid fevers", "category": "INFECTIOUS"},
    {"code": "A02", "description": "Other salmonella infections", "category": "INFECTIOUS"},
    {"code": "A03", "description": "Shigellosis", "category": "INFECTIOUS"},
    {"code": "A04", "description": "Other bacterial intestinal infections", "category": "INFECTIOUS"},
    {"code": "A05", "description": "Other bacterial foodborne intoxications", "category": "INFECTIOUS"},
    {"code": "A06", "description": "Amebiasis", "category": "INFECTIOUS"},
    {"code": "A07", "description": "Protozoal intestinal diseases", "category": "INFECTIOUS"},
    {"code": "A08", "description": "Viral intestinal infections", "category": "INFECTIOUS"},
    {"code": "A09", "description": "Infectious gastroenteritis and colitis", "category": "INFECTIOUS"},
    {"code": "B00", "description": "Herpesviral infections", "category": "INFECTIOUS"},
    {"code": "B01", "description": "Varicella", "category": "INFECTIOUS"},
    {"code": "B02", "description": "Zoster", "category": "INFECTIOUS"},
    {"code": "B03", "description": "Smallpox", "category": "INFECTIOUS"},
    {"code": "B04", "description": "Monkeypox", "category": "INFECTIOUS"},
    {"code": "C01", "description": "Malignant neoplasm of base of tongue", "category": "NEOPLASMS"},
    {"code": "C02", "description": "Malignant neoplasm of other parts of tongue", "category": "NEOPLASMS"},
    {"code": "C03", "description": "Malignant neoplasm of gum", "category": "NEOPLASMS"},
    {"code": "C04", "description": "Malignant neoplasm of floor of mouth", "category": "NEOPLASMS"},
    {"code": "C05", "description": "Malignant neoplasm of palate", "category": "NEOPLASMS"},
    {"code": "C06", "description": "Malignant neoplasm of other parts of mouth", "category": "NEOPLASMS"},
    {"code": "C07", "description": "Malignant neoplasm of parotid gland", "category": "NEOPLASMS"},
    {"code": "C08", "description": "Malignant neoplasm of other major salivary glands", "category": "NEOPLASMS"},
    {"code": "C09", "description": "Malignant neoplasm of tonsil", "category": "NEOPLASMS"},
    {"code": "D51", "description": "Vitamin B12 deficiency anemia", "category": "BLOOD"},
    {"code": "D52", "description": "Folate deficiency anemia", "category": "BLOOD"},
    {"code": "D53", "description": "Other nutritional anemias", "category": "BLOOD"},
    {"code": "D55", "description": "Anemia due to enzyme disorders", "category": "BLOOD"},
    {"code": "D56", "description": "Thalassemia", "category": "BLOOD"},
    {"code": "D57", "description": "Sickle-cell disorders", "category": "BLOOD"},
    {"code": "D58", "description": "Other hereditary hemolytic anemias", "category": "BLOOD"},
    {"code": "D59", "description": "Acquired hemolytic anemia", "category": "BLOOD"},
    {"code": "D60", "description": "Aplastic anemia", "category": "BLOOD"},
    {"code": "E00", "description": "Congenital iodine-deficiency syndrome", "category": "ENDOCRINE"},
    {"code": "E01", "description": "Iodine-deficiency related thyroid disorders", "category": "ENDOCRINE"},
    {"code": "E02", "description": "Subclinical iodine-deficiency hypothyroidism", "category": "ENDOCRINE"},
    {"code": "E03", "description": "Other hypothyroidism", "category": "ENDOCRINE"},
    {"code": "E04", "description": "Nontoxic goiter", "category": "ENDOCRINE"},
    {"code": "E05", "description": "Thyrotoxicosis", "category": "ENDOCRINE"},
    {"code": "E06", "description": "Thyroiditis", "category": "ENDOCRINE"},
    {"code": "E07", "description": "Other disorders of thyroid", "category": "ENDOCRINE"},
    {"code": "E10", "description": "Type 1 diabetes mellitus", "category": "ENDOCRINE"},
    {"code": "E11", "description": "Type 2 diabetes mellitus", "category": "ENDOCRINE"},
    {"code": "E12", "description": "Malnutrition-related diabetes mellitus", "category": "ENDOCRINE"},
    {"code": "E13", "description": "Other specified diabetes mellitus", "category": "ENDOCRINE"},
    {"code": "E14", "description": "Unspecified diabetes mellitus", "category": "ENDOCRINE"},
    {"code": "E15", "description": "Nondiabetic hypoglycemic coma", "category": "ENDOCRINE"},
    {"code": "E16", "description": "Other disorders of pancreatic internal secretion", "category": "ENDOCRINE"},
    {"code": "F00", "description": "Dementia in Alzheimer disease", "category": "MENTAL"},
    {"code": "F01", "description": "Vascular dementia", "category": "MENTAL"},
    {"code": "F02", "description": "Dementia in other diseases classified elsewhere", "category": "MENTAL"},
    {"code": "F03", "description": "Unspecified dementia", "category": "MENTAL"},
    {"code": "F04", "description": "Organic amnestic syndrome", "category": "MENTAL"},
    {"code": "F05", "description": "Delirium", "category": "MENTAL"},
    {"code": "F06", "description": "Other mental disorders due to brain damage", "category": "MENTAL"},
    {"code": "F07", "description": "Personality and behavioral disorders due to brain disease", "category": "MENTAL"},
    {"code": "F08", "description": "Other mental disorders due to brain damage", "category": "MENTAL"},
    {"code": "F09", "description": "Unspecified mental disorder due to brain damage", "category": "MENTAL"},
    {"code": "F10", "description": "Mental disorders due to alcohol use", "category": "MENTAL"},
    {"code": "F11", "description": "Mental disorders due to opioid use", "category": "MENTAL"},
    {"code": "F12", "description": "Mental disorders due to cannabis use", "category": "MENTAL"},
    {"code": "F13", "description": "Mental disorders due to sedative use", "category": "MENTAL"},
    {"code": "F14", "description": "Mental disorders due to cocaine use", "category": "MENTAL"},
    {"code": "G00", "description": "Meningitis due to bacteria", "category": "NERVOUS"},
    {"code": "G01", "description": "Meningitis in bacterial diseases classified elsewhere", "category": "NERVOUS"},
    {"code": "G02", "description": "Meningitis in other infectious diseases", "category": "NERVOUS"},
    {"code": "G03", "description": "Meningitis due to other causes", "category": "NERVOUS"},
    {"code": "G04", "description": "Encephalitis", "category": "NERVOUS"},
    {"code": "G05", "description": "Encephalitis in other diseases classified elsewhere", "category": "NERVOUS"},
    {"code": "G06", "description": "Intracranial abscess", "category": "NERVOUS"},
    {"code": "G07", "description": "Intracranial and intraspinal abscess", "category": "NERVOUS"},
    {"code": "G08", "description": "Intracranial and intraspinal phlebitis", "category": "NERVOUS"},
    {"code": "G09", "description": "Sequelae of inflammatory diseases of CNS", "category": "NERVOUS"},
    {"code": "H00", "description": "Hordeolum and chalazion", "category": "EYE"},
    {"code": "H01", "description": "Other inflammation of eyelid", "category": "EYE"},
    {"code": "H02", "description": "Other disorders of eyelid", "category": "EYE"},
    {"code": "H03", "description": "Disorders of eyelid in diseases classified elsewhere", "category": "EYE"},
    {"code": "H04", "description": "Disorders of lacrimal system", "category": "EYE"},
    {"code": "H05", "description": "Disorders of orbit", "category": "EYE"},
    {"code": "H10", "description": "Conjunctivitis", "category": "EYE"},
    {"code": "H11", "description": "Other disorders of conjunctiva", "category": "EYE"},
    {"code": "H15", "description": "Disorders of sclera", "category": "EYE"},
    {"code": "H16", "description": "Keratitis", "category": "EYE"},
    {"code": "H17", "description": "Corneal scars and opacities", "category": "EYE"},
    {"code": "H18", "description": "Other corneal disorders", "category": "EYE"},
    {"code": "H19", "description": "Disorders of sclera and cornea in diseases classified elsewhere", "category": "EYE"},
    {"code": "H20", "description": "Iridocyclitis", "category": "EYE"},
    {"code": "H21", "description": "Other disorders of iris and ciliary body", "category": "EYE"},
    {"code": "H22", "description": "Disorders of iris and ciliary body in diseases classified elsewhere", "category": "EYE"},
    {"code": "H25", "description": "Senile cataract", "category": "EYE"},
    {"code": "H26", "description": "Other cataract", "category": "EYE"},
    {"code": "H27", "description": "Other lens disorders", "category": "EYE"},
    {"code": "H30", "description": "Chorioretinal inflammation", "category": "EYE"},
    {"code": "H31", "description": "Other retinal disorders", "category": "EYE"},
    {"code": "H32", "description": "Chorioretinal disorders in diseases classified elsewhere", "category": "EYE"},
    {"code": "H33", "description": "Retinal detachment", "category": "EYE"},
    {"code": "H34", "description": "Retinal vascular occlusions", "category": "EYE"},
    {"code": "H35", "description": "Other retinal disorders", "category": "EYE"},
    {"code": "H36", "description": "Retinal disorders in diseases classified elsewhere", "category": "EYE"},
    {"code": "H40", "description": "Glaucoma", "category": "EYE"},
    {"code": "H42", "description": "Glaucoma in diseases classified elsewhere", "category": "EYE"},
    {"code": "H43", "description": "Disorders of vitreous body", "category": "EYE"},
    {"code": "H44", "description": "Disorders of globe", "category": "EYE"},
    {"code": "H45", "description": "Disorders of vitreous body and globe in diseases classified elsewhere", "category": "EYE"},
    {"code": "H46", "description": "Optic neuritis", "category": "EYE"},
    {"code": "H47", "description": "Other disorders of optic nerve", "category": "EYE"},
    {"code": "H48", "description": "Optic nerve disorders in diseases classified elsewhere", "category": "EYE"},
    {"code": "H49", "description": "Strabismus", "category": "EYE"},
    {"code": "H50", "description": "Other strabismus", "category": "EYE"},
    {"code": "H51", "description": "Other binocular vision disorders", "category": "EYE"},
    {"code": "H52", "description": "Disorders of refraction and accommodation", "category": "EYE"},
    {"code": "H53", "description": "Visual disturbances", "category": "EYE"},
    {"code": "H54", "description": "Blindness and low vision", "category": "EYE"},
    {"code": "H55", "description": "Nystagmus", "category": "EYE"},
    {"code": "H57", "description": "Other disorders of eye and adnexa", "category": "EYE"},
    {"code": "H58", "description": "Disorders of eye and adnexa in diseases classified elsewhere", "category": "EYE"},
    {"code": "H59", "description": "Disorders of eye and adnexa following procedures", "category": "EYE"},
    {"code": "H60", "description": "Otitis externa", "category": "EAR"},
    {"code": "H61", "description": "Other disorders of external ear", "category": "EAR"},
    {"code": "H62", "description": "Disorders of external ear in diseases classified elsewhere", "category": "EAR"},
    {"code": "H65", "description": "Nonsuppurative otitis media", "category": "EAR"},
    {"code": "H66", "description": "Suppurative otitis media", "category": "EAR"},
    {"code": "H67", "description": "Otitis media in diseases classified elsewhere", "category": "EAR"},
    {"code": "H68", "description": "Salpingitis and Eustachian tube disorders", "category": "EAR"},
    {"code": "H69", "description": "Other disorders of Eustachian tube", "category": "EAR"},
    {"code": "H70", "description": "Mastoiditis", "category": "EAR"},
    {"code": "H71", "description": "Petrositis", "category": "EAR"},
    {"code": "H72", "description": "Perforation of tympanic membrane", "category": "EAR"},
    {"code": "H73", "description": "Other disorders of tympanic membrane", "category": "EAR"},
    {"code": "H74", "description": "Other disorders of middle ear and mastoid", "category": "EAR"},
    {"code": "H75", "description": "Other disorders of middle ear in diseases classified elsewhere", "category": "EAR"},
    {"code": "H80", "description": "Otosclerosis", "category": "EAR"},
    {"code": "H81", "description": "Vertigo", "category": "EAR"},
    {"code": "H82", "description": "Vertigo in diseases classified elsewhere", "category": "EAR"},
    {"code": "H83", "description": "Other diseases of inner ear", "category": "EAR"},
    {"code": "H90", "description": "Conductive hearing loss", "category": "EAR"},
    {"code": "H91", "description": "Sensorineural hearing loss", "category": "EAR"},
    {"code": "H92", "description": "Other hearing loss", "category": "EAR"},
    {"code": "H93", "description": "Other disorders of ear", "category": "EAR"},
    {"code": "H94", "description": "Disorders of ear in diseases classified elsewhere", "category": "EAR"},
    {"code": "H95", "description": "Postprocedural disorders of ear", "category": "EAR"},
    {"code": "I00", "description": "Rheumatic fever", "category": "CIRCULATORY"},
    {"code": "I01", "description": "Rheumatic heart disease", "category": "CIRCULATORY"},
    {"code": "I02", "description": "Sydenham chorea", "category": "CIRCULATORY"},
    {"code": "I05", "description": "Rheumatic mitral valve diseases", "category": "CIRCULATORY"},
    {"code": "I06", "description": "Rheumatic aortic valve diseases", "category": "CIRCULATORY"},
    {"code": "I07", "description": "Rheumatic tricuspid valve diseases", "category": "CIRCULATORY"},
    {"code": "I08", "description": "Multiple valve diseases", "category": "CIRCULATORY"},
    {"code": "I09", "description": "Other rheumatic heart diseases", "category": "CIRCULATORY"},
    {"code": "I10", "description": "Essential hypertension", "category": "CIRCULATORY"},
    {"code": "I11", "description": "Hypertensive heart disease", "category": "CIRCULATORY"},
    {"code": "I12", "description": "Hypertensive chronic kidney disease", "category": "CIRCULATORY"},
    {"code": "I13", "description": "Hypertensive heart and chronic kidney disease", "category": "CIRCULATORY"},
    {"code": "I14", "description": "Secondary hypertension", "category": "CIRCULATORY"},
    {"code": "I15", "description": "Hypertensive emergency", "category": "CIRCULATORY"},
    {"code": "I20", "description": "Angina pectoris", "category": "CIRCULATORY"},
    {"code": "I21", "description": "Acute myocardial infarction", "category": "CIRCULATORY"},
    {"code": "I22", "description": "Subsequent myocardial infarction", "category": "CIRCULATORY"},
    {"code": "I23", "description": "Certain current complications following acute myocardial infarction", "category": "CIRCULATORY"},
    {"code": "I24", "description": "Other acute ischemic heart diseases", "category": "CIRCULATORY"},
    {"code": "I25", "description": "Chronic ischemic heart disease", "category": "CIRCULATORY"},
    {"code": "I26", "description": "Pulmonary embolism", "category": "CIRCULATORY"},
    {"code": "I27", "description": "Other pulmonary heart diseases", "category": "CIRCULATORY"},
    {"code": "I28", "description": "Other diseases of pulmonary vessels", "category": "CIRCULATORY"},
    {"code": "I30", "description": "Acute pericarditis", "category": "CIRCULATORY"},
    {"code": "I31", "description": "Other diseases of pericardium", "category": "CIRCULATORY"},
    {"code": "I32", "description": "Pericarditis in diseases classified elsewhere", "category": "CIRCULATORY"},
    {"code": "I33", "description": "Acute and subacute endocarditis", "category": "CIRCULATORY"},
    {"code": "I34", "description": "Nonrheumatic mitral valve disorders", "category": "CIRCULATORY"},
    {"code": "I35", "description": "Nonrheumatic aortic valve disorders", "category": "CIRCULATORY"},
    {"code": "I36", "description": "Nonrheumatic tricuspid valve disorders", "category": "CIRCULATORY"},
    {"code": "I37", "description": "Nonrheumatic pulmonary valve disorders", "category": "CIRCULATORY"},
    {"code": "I38", "description": "Endocarditis, valve unspecified", "category": "CIRCULATORY"},
    {"code": "I39", "description": "Endocarditis and heart valve disorders in diseases classified elsewhere", "category": "CIRCULATORY"},
    {"code": "I40", "description": "Acute myocarditis", "category": "CIRCULATORY"},
    {"code": "I41", "description": "Myocarditis in diseases classified elsewhere", "category": "CIRCULATORY"},
    {"code": "I42", "description": "Cardiomyopathy", "category": "CIRCULATORY"},
    {"code": "I43", "description": "Cardiomyopathy in diseases classified elsewhere", "category": "CIRCULATORY"},
    {"code": "I44", "description": "Atrioventricular and left bundle-branch block", "category": "CIRCULATORY"},
    {"code": "I45", "description": "Other conduction disorders", "category": "CIRCULATORY"},
    {"code": "I46", "description": "Cardiac arrest", "category": "CIRCULATORY"},
    {"code": "I47", "description": "Paroxysmal tachycardia", "category": "CIRCULATORY"},
    {"code": "I48", "description": "Atrial fibrillation and flutter", "category": "CIRCULATORY"},
    {"code": "I49", "description": "Other cardiac arrhythmias", "category": "CIRCULATORY"},
    {"code": "I50", "description": "Heart failure", "category": "CIRCULATORY"},
    {"code": "I51", "description": "Complications of heart disease", "category": "CIRCULATORY"},
    {"code": "I52", "description": "Other heart disorders in diseases classified elsewhere", "category": "CIRCULATORY"},
    {"code": "I53", "description": "Postcardiac surgery syndromes", "category": "CIRCULATORY"},
    {"code": "I60", "description": "Subarachnoid hemorrhage", "category": "CIRCULATORY"},
    {"code": "I61", "description": "Intracerebral hemorrhage", "category": "CIRCULATORY"},
    {"code": "I62", "description": "Other nontraumatic intracranial hemorrhage", "category": "CIRCULATORY"},
    {"code": "I63", "description": "Cerebral infarction", "category": "CIRCULATORY"},
    {"code": "I64", "description": "Stroke, not specified as hemorrhage or infarction", "category": "CIRCULATORY"},
    {"code": "I65", "description": "Occlusion and stenosis of precerebral arteries", "category": "CIRCULATORY"},
    {"code": "I66", "description": "Occlusion and stenosis of cerebral arteries", "category": "CIRCULATORY"},
    {"code": "I67", "description": "Other cerebrovascular diseases", "category": "CIRCULATORY"},
    {"code": "I68", "description": "Cerebrovascular disorders in diseases classified elsewhere", "category": "CIRCULATORY"},
    {"code": "I69", "description": "Sequelae of cerebrovascular disease", "category": "CIRCULATORY"},
    {"code": "J00", "description": "Acute nasopharyngitis", "category": "RESPIRATORY"},
    {"code": "J01", "description": "Acute sinusitis", "category": "RESPIRATORY"},
    {"code": "J02", "description": "Acute pharyngitis", "category": "RESPIRATORY"},
    {"code": "J03", "description": "Acute tonsillitis", "category": "RESPIRATORY"},
    {"code": "J04", "description": "Acute laryngitis and tracheitis", "category": "RESPIRATORY"},
    {"code": "J05", "description": "Acute obstructive laryngitis and epiglottitis", "category": "RESPIRATORY"},
    {"code": "J06", "description": "Upper respiratory infections of multiple sites", "category": "RESPIRATORY"},
    {"code": "J10", "description": "Influenza due to identified influenza virus", "category": "RESPIRATORY"},
    {"code": "J11", "description": "Influenza, virus not identified", "category": "RESPIRATORY"},
    {"code": "J12", "description": "Viral pneumonia", "category": "RESPIRATORY"},
    {"code": "J13", "description": "Pneumonia due to Streptococcus pneumoniae", "category": "RESPIRATORY"},
    {"code": "J14", "description": "Pneumonia due to Haemophilus influenzae", "category": "RESPIRATORY"},
    {"code": "J15", "description": "Bacterial pneumonia", "category": "RESPIRATORY"},
    {"code": "J16", "description": "Pneumonia due to other infectious organisms", "category": "RESPIRATORY"},
    {"code": "J17", "description": "Pneumonia in diseases classified elsewhere", "category": "RESPIRATORY"},
    {"code": "J18", "description": "Pneumonia, unspecified organism", "category": "RESPIRATORY"},
    {"code": "J20", "description": "Acute bronchitis", "category": "RESPIRATORY"},
    {"code": "J21", "description": "Acute bronchiolitis", "category": "RESPIRATORY"},
    {"code": "J22", "description": "Lower respiratory infection, unspecified", "category": "RESPIRATORY"},
    {"code": "J30", "description": "Vasomotor and allergic rhinitis", "category": "RESPIRATORY"},
    {"code": "J31", "description": "Chronic rhinitis, nasopharyngitis and pharyngitis", "category": "RESPIRATORY"},
    {"code": "J32", "description": "Chronic sinusitis", "category": "RESPIRATORY"},
    {"code": "J33", "description": "Nasal polyp", "category": "RESPIRATORY"},
    {"code": "J34", "description": "Other disorders of nose and nasal sinuses", "category": "RESPIRATORY"},
    {"code": "J35", "description": "Chronic diseases of tonsils and adenoids", "category": "RESPIRATORY"},
    {"code": "J36", "description": "Peritonsillar abscess", "category": "RESPIRATORY"},
    {"code": "J37", "description": "Chronic laryngitis and laryngotracheitis", "category": "RESPIRATORY"},
    {"code": "J38", "description": "Diseases of vocal cords and larynx", "category": "RESPIRATORY"},
    {"code": "J39", "description": "Other diseases of upper respiratory tract", "category": "RESPIRATORY"},
    {"code": "J40", "description": "Bronchitis, not specified as acute or chronic", "category": "RESPIRATORY"},
    {"code": "J41", "description": "Simple and mucopurulent chronic bronchitis", "category": "RESPIRATORY"},
    {"code": "J42", "description": "Unspecified chronic bronchitis", "category": "RESPIRATORY"},
    {"code": "J43", "description": "Emphysema", "category": "RESPIRATORY"},
    {"code": "J44", "description": "Other chronic obstructive pulmonary disease", "category": "RESPIRATORY"},
    {"code": "J45", "description": "Asthma", "category": "RESPIRATORY"},
    {"code": "J46", "description": "Status asthmaticus", "category": "RESPIRATORY"},
    {"code": "J47", "description": "Bronchiectasis", "category": "RESPIRATORY"},
    {"code": "J60", "description": "Pneumoconiosis due to coal dust", "category": "RESPIRATORY"},
    {"code": "J61", "description": "Pneumoconiosis due to asbestos", "category": "RESPIRATORY"},
    {"code": "J62", "description": "Pneumoconiosis due to talc dust", "category": "RESPIRATORY"},
    {"code": "J63", "description": "Pneumoconiosis due to other inorganic dusts", "category": "RESPIRATORY"},
    {"code": "J64", "description": "Unspecified pneumoconiosis", "category": "RESPIRATORY"},
    {"code": "J65", "description": "Pneumoconiosis associated with tuberculosis", "category": "RESPIRATORY"},
    {"code": "J66", "description": "Airway disease due to organic dust", "category": "RESPIRATORY"},
    {"code": "J67", "description": "Hypersensitivity pneumonitis", "category": "RESPIRATORY"},
    {"code": "J68", "description": "Respiratory conditions due to chemicals, gases, and fumes", "category": "RESPIRATORY"},
    {"code": "J69", "description": "Respiratory conditions due to external agents", "category": "RESPIRATORY"},
    {"code": "J70", "description": "Respiratory conditions due to other external agents", "category": "RESPIRATORY"},
    {"code": "J80", "description": "Adult respiratory distress syndrome", "category": "RESPIRATORY"},
    {"code": "J81", "description": "Pulmonary edema", "category": "RESPIRATORY"},
    {"code": "J82", "description": "Pulmonary eosinophilia", "category": "RESPIRATORY"},
    {"code": "J84", "description": "Other interstitial pulmonary diseases", "category": "RESPIRATORY"},
    {"code": "J85", "description": "Abscess of lung and mediastinum", "category": "RESPIRATORY"},
    {"code": "J86", "description": "Pyohemothorax", "category": "RESPIRATORY"},
    {"code": "J90", "description": "Pleural effusion, not elsewhere classified", "category": "RESPIRATORY"},
    {"code": "J91", "description": "Pleural effusion in diseases classified elsewhere", "category": "RESPIRATORY"},
    {"code": "J92", "description": "Pleural plaque", "category": "RESPIRATORY"},
    {"code": "J93", "description": "Pneumothorax", "category": "RESPIRATORY"},
    {"code": "J94", "description": "Other pleural conditions", "category": "RESPIRATORY"},
    {"code": "J95", "description": "Intrathoracic disorders following procedures", "category": "RESPIRATORY"},
    {"code": "J96", "description": "Respiratory failure", "category": "RESPIRATORY"},
    {"code": "J97", "description": "Respiratory failure in diseases classified elsewhere", "category": "RESPIRATORY"},
    {"code": "J98", "description": "Other respiratory disorders", "category": "RESPIRATORY"},
    {"code": "J99", "description": "Respiratory disorders in diseases classified elsewhere", "category": "RESPIRATORY"},
)


PROCEDURE_CODES = (
    {"code": "70010", "description": "Radiologic examination, skull", "category": "DIAGNOSTIC"},
    {"code": "80000", "description": "Pathology and laboratory", "category": "LABORATORY"},
    {"code": "99201", "description": "Office visit new patient level 1", "category": "EVALUATION"},
    {"code": "99281", "description": "Emergency department visit level 1", "category": "EMERGENCY"},
    {"code": "10060", "description": "Incision and drainage of abscess", "category": "SURGERY"},
    {"code": "99202", "description": "Office visit new patient level 2", "category": "EVALUATION"},
    {"code": "99203", "description": "Office visit new patient level 3", "category": "EVALUATION"},
    {"code": "99204", "description": "Office visit new patient level 4", "category": "EVALUATION"},
    {"code": "99205", "description": "Office visit new patient level 5", "category": "EVALUATION"},
    {"code": "99211", "description": "Office visit established patient level 1", "category": "EVALUATION"},
    {"code": "99212", "description": "Office visit established patient level 2", "category": "EVALUATION"},
    {"code": "99213", "description": "Office visit established patient level 3", "category": "EVALUATION"},
    {"code": "99214", "description": "Office visit established patient level 4", "category": "EVALUATION"},
    {"code": "99215", "description": "Office visit established patient level 5", "category": "EVALUATION"},
    {"code": "99221", "description": "Initial hospital care level 1", "category": "EVALUATION"},
    {"code": "99222", "description": "Initial hospital care level 2", "category": "EVALUATION"},
    {"code": "99223", "description": "Initial hospital care level 3", "category": "EVALUATION"},
    {"code": "99231", "description": "Subsequent hospital care level 1", "category": "EVALUATION"},
    {"code": "99232", "description": "Subsequent hospital care level 2", "category": "EVALUATION"},
    {"code": "99233", "description": "Subsequent hospital care level 3", "category": "EVALUATION"},
    {"code": "99238", "description": "Hospital discharge day management", "category": "EVALUATION"},
    {"code": "99239", "description": "Hospital discharge day management extended", "category": "EVALUATION"},
    {"code": "99282", "description": "Emergency department visit level 2", "category": "EMERGENCY"},
    {"code": "99283", "description": "Emergency department visit level 3", "category": "EMERGENCY"},
    {"code": "99284", "description": "Emergency department visit level 4", "category": "EMERGENCY"},
    {"code": "99285", "description": "Emergency department visit level 5", "category": "EMERGENCY"},
    {"code": "99286", "description": "Critical care emergency department visit", "category": "EMERGENCY"},
    {"code": "99287", "description": "Pediatric emergency visit", "category": "EMERGENCY"},
    {"code": "99288", "description": "Trauma emergency visit", "category": "EMERGENCY"},
    {"code": "99304", "description": "Initial nursing facility care level 1", "category": "EVALUATION"},
    {"code": "99305", "description": "Initial nursing facility care level 2", "category": "EVALUATION"},
    {"code": "99306", "description": "Initial nursing facility care level 3", "category": "EVALUATION"},
    {"code": "99307", "description": "Subsequent nursing facility care level 1", "category": "EVALUATION"},
    {"code": "99308", "description": "Subsequent nursing facility care level 2", "category": "EVALUATION"},
    {"code": "99309", "description": "Subsequent nursing facility care level 3", "category": "EVALUATION"},
    {"code": "99310", "description": "Subsequent nursing facility care level 4", "category": "EVALUATION"},
    {"code": "99324", "description": "Home visit new patient level 1", "category": "EVALUATION"},
    {"code": "99325", "description": "Home visit new patient level 2", "category": "EVALUATION"},
    {"code": "99326", "description": "Home visit new patient level 3", "category": "EVALUATION"},
    {"code": "99327", "description": "Home visit new patient level 4", "category": "EVALUATION"},
    {"code": "99328", "description": "Home visit new patient level 5", "category": "EVALUATION"},
    {"code": "99334", "description": "Home visit established patient level 1", "category": "EVALUATION"},
    {"code": "99335", "description": "Home visit established patient level 2", "category": "EVALUATION"},
    {"code": "99336", "description": "Home visit established patient level 3", "category": "EVALUATION"},
    {"code": "99337", "description": "Home visit established patient level 4", "category": "EVALUATION"},
    {"code": "99339", "description": "Home visit chronic care management", "category": "EVALUATION"},
    {"code": "99340", "description": "Home visit preventive medicine", "category": "EVALUATION"},
    {"code": "99341", "description": "Home visit new patient level 1", "category": "EVALUATION"},
    {"code": "99342", "description": "Home visit new patient level 2", "category": "EVALUATION"},
    {"code": "99343", "description": "Home visit new patient level 3", "category": "EVALUATION"},
    {"code": "99344", "description": "Home visit new patient level 4", "category": "EVALUATION"},
    {"code": "99345", "description": "Home visit new patient level 5", "category": "EVALUATION"},
    {"code": "99347", "description": "Home visit established patient level 1", "category": "EVALUATION"},
    {"code": "99348", "description": "Home visit established patient level 2", "category": "EVALUATION"},
    {"code": "99349", "description": "Home visit established patient level 3", "category": "EVALUATION"},
    {"code": "99350", "description": "Home visit established patient level 4", "category": "EVALUATION"},
    {"code": "10061", "description": "Incision and drainage of complex abscess", "category": "SURGERY"},
    {"code": "10120", "description": "Removal of foreign body from subcutaneous tissue", "category": "SURGERY"},
    {"code": "10140", "description": "Incision and drainage of hematoma", "category": "SURGERY"},
    {"code": "11000", "description": "Debridement of skin and subcutaneous tissue", "category": "SURGERY"},
    {"code": "11001", "description": "Debridement of skin and subcutaneous tissue extensive", "category": "SURGERY"},
    {"code": "11002", "description": "Debridement of skin and subcutaneous tissue with grafting", "category": "SURGERY"},
    {"code": "11003", "description": "Debridement of skin and subcutaneous tissue with flap", "category": "SURGERY"},
    {"code": "11004", "description": "Debridement of skin and subcutaneous tissue with skin graft", "category": "SURGERY"},
    {"code": "11005", "description": "Debridement of skin and subcutaneous tissue with muscle graft", "category": "SURGERY"},
    {"code": "11006", "description": "Debridement of skin and subcutaneous tissue with bone graft", "category": "SURGERY"},
    {"code": "11007", "description": "Debridement of skin and subcutaneous tissue with vascularized flap", "category": "SURGERY"},
    {"code": "11008", "description": "Debridement of skin and subcutaneous tissue with tissue transfer", "category": "SURGERY"},
    {"code": "11009", "description": "Debridement of skin and subcutaneous tissue with other procedure", "category": "SURGERY"},
)

COUNTRIES = (
    {"code": "IN", "name": "India"},
)

STATES = (
    {"code": "MH", "name": "Maharashtra"},
    {"code": "DL", "name": "Delhi"},
    {"code": "KA", "name": "Karnataka"},
    {"code": "TN", "name": "Tamil Nadu"},
    {"code": "GJ", "name": "Gujarat"},
    {"code": "RJ", "name": "Rajasthan"},
    {"code": "UP", "name": "Uttar Pradesh"},
    {"code": "WB", "name": "West Bengal"},
    {"code": "KL", "name": "Kerala"},
    {"code": "TS", "name": "Telangana"},
    {"code": "AP", "name": "Andhra Pradesh"},
    {"code": "MP", "name": "Madhya Pradesh"},
    {"code": "HR", "name": "Haryana"},
    {"code": "PB", "name": "Punjab"},
    {"code": "BR", "name": "Bihar"},
    {"code": "OR", "name": "Odisha"},
    {"code": "AS", "name": "Assam"},
    {"code": "GA", "name": "Goa"},
    {"code": "CH", "name": "Chandigarh"},
    {"code": "JK", "name": "Jammu and Kashmir"},
)

CITIES = (
    {"code": "BOM", "name": "Mumbai", "state_code": "MH"},
    {"code": "DEL", "name": "New Delhi", "state_code": "DL"},
    {"code": "BLR", "name": "Bangalore", "state_code": "KA"},
    {"code": "MAA", "name": "Chennai", "state_code": "TN"},
    {"code": "AHM", "name": "Ahmedabad", "state_code": "GJ"},
    {"code": "JAI", "name": "Jaipur", "state_code": "RJ"},
    {"code": "LUC", "name": "Lucknow", "state_code": "UP"},
    {"code": "KOL", "name": "Kolkata", "state_code": "WB"},
    {"code": "COC", "name": "Kochi", "state_code": "KL"},
    {"code": "HYD", "name": "Hyderabad", "state_code": "TS"},
    {"code": "PUN", "name": "Pune", "state_code": "MH"},
    {"code": "SUR", "name": "Surat", "state_code": "GJ"},
    {"code": "IND", "name": "Indore", "state_code": "MP"},
    {"code": "LUD", "name": "Ludhiana", "state_code": "PB"},
    {"code": "NAG", "name": "Nagpur", "state_code": "MH"},
    {"code": "BHO", "name": "Bhopal", "state_code": "MP"},
    {"code": "PAT", "name": "Patna", "state_code": "BR"},
    {"code": "AGR", "name": "Agra", "state_code": "UP"},
    {"code": "VAD", "name": "Vadodara", "state_code": "GJ"},
    {"code": "GOA", "name": "Goa", "state_code": "GA"},
)

